### ISSUE TITLE
First time seeing Hosts

### ISSUE THREAD

**Issue by james2649** [dragokas/hijackthis#191]
On a recent scan  started seeing hosts listed with IP address 127.0.0.0 and various domains -- Screenshot attached.
I have XAMPP with a local server.
I thought  127.0.0.0 was only local and not accessible by internet
![20221110_CAP_](https://user-images.githubusercontent.com/117945749/201197443-129dade0-4a91-4597-8b3e-362ab4663e22.jpg)

Is this something to be concerned about?
I've tried "fix" but hosts remain.

Thanks for any advice or help,

James Pickett

**Comment by Sandor-Helper** [comment]
Hi,
If you need our assistance:
 
* Read carefully: [How to make a request for help in the PC cure section](https://github.com/dragokas/hijackthis/wiki/How-to-make-a-request-for-help-in-the-PC-cure-section%3F)
* Attach 'Collection-[Date].zip' log created by [AutoLogger](https://safezone.cc/resources/autologger-regist-drongo.59/download)
 
**Please, note that only members of [VIRUSNET-Association](https://github.com/VIRUSNET-Association) are allowed to respond to PC cure topics. Ignore any recommendations given by other users, including PM !!!**

**Assistance is provided free of charge in our free time. If you found our help useful, you can thank us with any amount using [this form](https://safezone.cc/donate/) or you can leave feedback in [Guestbook](https://github.com/dragokas/hijackthis/issues/47).**

**Comment by james2649** [comment]
[CollectionLog-2022.11.11-09.40.zip](https://github.com/dragokas/hijackthis/files/9991346/CollectionLog-2022.11.11-09.40.zip)

Also in the last couple of days the mouse and keyboard on this computer have become erratic and freezes. I  computers on a KVM switch and mouse performs er two computers  without issues.

**Comment by Sandor-Helper** [comment]
Please download [Farbar Recovery Scan Tool](https://www.bleepingcomputer.com/download/farbar-recovery-scan-tool/) and save it to your Desktop.

**Note**: You need to run the version compatible with your system. If you are not sure which version applies to your system download both of them and try to run them. Only one of them will run on your system, that will be the right version.

- Right click to run as administrator. When the tool opens click **Yes** to disclaimer.
- Press **Scan** button.
- It will produce logs called **FRST.txt** and **Addition.txt** in the same directory the tool is run from.
- Please attach the logs back here.

**Comment by james2649** [comment]
[CollectionLog-2022.11.11-09.40.zip](https://github.com/dragokas/hijackthis/files/9991346/CollectionLog-2022.11.11-09.40.zip)

Also in the last couple of days the mouse and keyboard on this computer have become erratic and freezes. I  computers on a KVM switch and mouse performs er two computers  without issues.

**Comment by james2649** [comment]
Thanks. I ran FRST.
Everything was white listed; no fixlist.

Pertinent to Hosts is --

IPSecPolicy: [ActivePolicy] SOFTWARE\Policies\Microsoft\Windows\IPSEC\Policy\Local\ipsecPolicy{7ff9a010-ca7f-4876-b064-2038df06158a} <==== ATTENTION (Restriction - IP)
Hosts: There are more than one entry in Hosts. See Hosts section of Addition.txt   [follows]

==================== Hosts content: =========================

(If needed Hosts: directive could be included in the fixlist to reset Hosts.)

2022-11-10 15:45 - 2022-11-10 15:45 - 000451400 ____R C:\WINDOWS\system32\drivers\etc\hosts
127.0.0.1	activate.adobe.com
127.0.0.1	www.008k.com
127.0.0.1	008k.com
127.0.0.1	www.00hq.com
127.0.0.1	00hq.com
127.0.0.1	010402.com
127.0.0.1	www.032439.com
127.0.0.1	032439.com
127.0.0.1	10sek.com
127.0.0.1	www.10sek.com
127.0.0.1	www.1-2005-search.com
127.0.0.1	1-2005-search.com
127.0.0.1	123fporn.info
127.0.0.1	www.123fporn.info
127.0.0.1	www.123haustiereundmehr.com
127.0.0.1	123haustiereundmehr.com
127.0.0.1	123moviedownload.com
127.0.0.1	www.123moviedownload.com
127.0.0.1	123simsen.com
127.0.0.1	www.123simsen.com
127.0.0.1	123topsearch.com
127.0.0.1	2008-search-destroy.com
127.0.0.1	2008-viewer.com
127.0.0.1	www.2008-viewer.com
127.0.0.1	2009--access.com
127.0.0.1	www.2009--access.com
127.0.0.1	www.2009antivirpro.com
127.0.0.1	2009antivirpro.com
127.0.0.1	www.2009-edition.com
127.0.0.1	2009-edition.com

There are 15492 more lines.
=======================================================
[Addition.txt](https://github.com/dragokas/hijackthis/files/9997652/Addition.txt)
[FRST.txt](https://github.com/dragokas/hijackthis/files/9997654/FRST.txt)
=========================================================

Should I run fix on  Hosts: directive ?
As long as hosts is not malware, I don't mind it appearing in HijackThis.

Reviewing, these appeared after I installed and ran 'SpyBot - Search & Destroy' as a portable app.
I uninstalled SpyBot and the erratic behavior of the mouse mouse and keyboard have resolved.

Thanks, again, for you help and advice.

**Comment by Sandor-Helper** [comment]
Sorry for delaying answer. Right, SpyBot is useless tool and it should not be installed.
I'd like to clarify - is your problem solved now?

If you like we can do a kind of general cleaning by deleting some temp files in your system.

**Comment by james2649** [comment]
Computer functions well. No problem with mouse, keyboard or computing.

But, when I scan with Hijackthis, I still get long list of hosts, as first noted.
Should I run fix on Hosts: directive ?
As long as hosts is not malware, I don't mind it appearing in HijackThis.

Thanks.

**Comment by james2649** [comment]
Could this be due to the Microsoft Edge browser? Edge has an option to block malicious sites.

**Comment by Sandor-Helper** [comment]
Ok, lets fix it.

Download attached file fixlist.txt and place it in the same folder where FRST64.exe is (C:\Users\dell24\Downloads).

Run program as administrator and press Fix button.
Get a patience because script could take a lot of time to run.
At the end PC will reboot and while rebooting there will start disk check for probably errors. Do not interupt it.
After restart please find in same folder file named Fixlog.txt and attach it to your next post.

[fixlist.txt](https://github.com/dragokas/hijackthis/files/10018798/fixlist.txt)

**Comment by james2649** [comment]
I downloaded fixlist.txt; ran FRST64.exe
Multiple folders were deleted.
Computer restart with Drive C fix 100% complete
[Fixlog.txt](https://github.com/dragokas/hijackthis/files/10024477/Fixlog.txt)
Fixlog.txt  in FRST folder, attached
Ran Hijackthis - no 01 Hosts alert posted.
Everything appears to be working well.

Is there something else you want me to do?

If not, you help and instruction much appreciated. Thank you.
-- James

**Comment by Sandor-Helper** [comment]
Thanks for the log. It was good run.
You have a lot of exclusions in Windows Defender such as whole discs and Programs folders etc. It is not right behavior in my opinion.
Can you mannually delete these exclusions or would you like me to write a script to do this?

**Comment by james2649** [comment]
Thanks for the offer.

I have multiple redundant backups that contain Nir-Soft scripts that Windows hates. So, the exclusions are for the redundant drives. 

All active work is done on run-protected drive then backed up to appropriate drive.  I'm OK with this. 

Thanks, again. I really do appreciate your advice and directions.

-- James
